//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity_uruntakip
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class entity_urunEntities : DbContext
    {
        public entity_urunEntities()
            : base("name=entity_urunEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_category> tbl_category { get; set; }
        public virtual DbSet<tbl_musteri> tbl_musteri { get; set; }
        public virtual DbSet<tbl_satis> tbl_satis { get; set; }
        public virtual DbSet<tbl_urun> tbl_urun { get; set; }
        public virtual DbSet<tbl_kullanici> tbl_kullanici { get; set; }
    
        public virtual ObjectResult<string> markagetir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("markagetir");
        }
    }
}
