//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity_uruntakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kullanici
    {
        public byte kullanici_id { get; set; }
        public string kullanici_adi { get; set; }
        public string kullanici_sifre { get; set; }
    }
}
